# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Ємець0_0\worker1\SUPER_DUPER_OMEGA_PAPKA\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 593)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.note = QtWidgets.QTextEdit(self.centralwidget)
        self.note.setGeometry(QtCore.QRect(10, 10, 431, 541))
        self.note.setStyleSheet("background-color:rgb(233, 247, 255);\n"
"border-radius:20px\n"
"")
        self.note.setObjectName("note")
        self.list_notes = QtWidgets.QListWidget(self.centralwidget)
        self.list_notes.setGeometry(QtCore.QRect(450, 20, 291, 181))
        self.list_notes.setStyleSheet("background-color:rgb(215, 255, 203);\n"
"border-radius:20px")
        self.list_notes.setObjectName("list_notes")
        self.list_notes_label = QtWidgets.QLabel(self.centralwidget)
        self.list_notes_label.setGeometry(QtCore.QRect(560, 0, 81, 20))
        self.list_notes_label.setObjectName("list_notes_label")
        self.list_tags = QtWidgets.QListWidget(self.centralwidget)
        self.list_tags.setGeometry(QtCore.QRect(450, 290, 291, 161))
        self.list_tags.setStyleSheet("background-color:rgb(215, 255, 203);\n"
"border-radius:20px")
        self.list_tags.setObjectName("list_tags")
        self.btn_note_crate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_note_crate.setGeometry(QtCore.QRect(450, 210, 141, 23))
        self.btn_note_crate.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(112, 22, 120)")
        self.btn_note_crate.setObjectName("btn_note_crate")
        self.btn_note_del = QtWidgets.QPushButton(self.centralwidget)
        self.btn_note_del.setGeometry(QtCore.QRect(610, 210, 131, 23))
        self.btn_note_del.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(112, 22, 120)")
        self.btn_note_del.setObjectName("btn_note_del")
        self.btn_note_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_note_save.setGeometry(QtCore.QRect(450, 240, 291, 23))
        self.btn_note_save.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(112, 22, 120)")
        self.btn_note_save.setObjectName("btn_note_save")
        self.list_text_label = QtWidgets.QLabel(self.centralwidget)
        self.list_text_label.setGeometry(QtCore.QRect(560, 270, 71, 20))
        self.list_text_label.setObjectName("list_text_label")
        self.btn_tag_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tag_add.setGeometry(QtCore.QRect(450, 490, 141, 23))
        self.btn_tag_add.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(112, 22, 120)")
        self.btn_tag_add.setObjectName("btn_tag_add")
        self.btn_tag_del = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tag_del.setGeometry(QtCore.QRect(600, 490, 141, 23))
        self.btn_tag_del.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(112, 22, 120)")
        self.btn_tag_del.setObjectName("btn_tag_del")
        self.btn_tag_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tag_search.setGeometry(QtCore.QRect(450, 520, 291, 23))
        self.btn_tag_search.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(112, 22, 120)")
        self.btn_tag_search.setObjectName("btn_tag_search")
        self.field_tag_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.field_tag_2.setGeometry(QtCore.QRect(450, 460, 291, 20))
        self.field_tag_2.setObjectName("field_tag_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Розумні Замітки"))
        self.note.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.list_notes_label.setText(_translate("MainWindow", "Список заміток"))
        self.btn_note_crate.setText(_translate("MainWindow", "Створити замітку"))
        self.btn_note_del.setText(_translate("MainWindow", "Видалити замітку"))
        self.btn_note_save.setText(_translate("MainWindow", "Зберегти замітку"))
        self.list_text_label.setText(_translate("MainWindow", "Список тегів"))
        self.btn_tag_add.setText(_translate("MainWindow", "Додати до замітки"))
        self.btn_tag_del.setText(_translate("MainWindow", "Відлкрипити від замітки"))
        self.btn_tag_search.setText(_translate("MainWindow", "Шукати замітку по тегу"))
        self.field_tag_2.setPlaceholderText("Введіть тег...")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
